system:
  name: SmartTraffy_00

stream:
  camera_1_url: rtsp://192.168.1.100/live   # stream1
  camera_2_url: rtsp://192.168.1.101/live   # stream2
  camera_3_url: rtsp://192.168.1.102/live   # stream3
  camera_4_url: rtsp://192.168.1.103/live   # stream4

traffic:
  seqence: [lamp_1, lamp_2, lamp_3, lamp_4]   # seqence of lamp order
  yellow_delay: 3   # yellow delay
  lamp_1_set_color: green   # color to apply delay time (green or red)
  lamp_1_time: 30   # delay time to apply to selected color
  lamp_2_set_color: green
  lamp_2_time: 30
  lamp_3_set_color: green
  lamp_3_time: 30
  lamp_4_set_color: green
  lamp_4_time: 30

mqtt:
  server: 192.168.1.14   # mqtt server address or hostname
  port: 1883    # mqtt server port
  username: controller    # mqtt user
  password: Nae/buf=o3jo    # mqtt password
  qos: 0    # mqtt quality of services
  version: 3.1.1    # mqtt protocol version 3.1, 3.1.1 or 5
  mac_id: true    # append mac address after system name for mqtt client id
  reconn_interval: 10   # try to reconnect every x seconds if connection lost.

yolo:
  model_path: yolov5    # model directory path
  weights: yolov5n-7.pt   # model.pt path(s)
  data: coco128.yaml    # dataset.yaml path
  conf_thres: 0.25    # confidence threshold
  iou_thres: 0.45   # NMS IOU threshold
  max_det: 1000   # maximum detections per image
  img_size: 640   # inference size h,w
  device: 0   # cuda device, i.e. 0 or 0,1,2,3 or cpu
  view_img: true    # show results
  save_txt: false   # save results to *.txt
  save_conf: false    # save confidences in --save-txt labels
  save_crop: false    # save cropped prediction boxes
  nosave: true    # do not save images/videos
  classes: [0, 1, 2, 3, 5, 7]   # filter by class from dataset file
  agnostic_nms: false   # class-agnostic NMS
  augment: false    # augmented inference
  visualize: false    # visualize features
  update: false   # update all models
  project: runs/detect    # save results to project/name
  name: exp   # save results to project/name
  exist_ok: false   # existing project/name ok, do not increment
  line_thickness: 2   # bounding box thickness (pixels)
  hide_labels: false    # hide labels
  hide_conf: false    # hide confidences
  half: false   # use FP16 half-precision inference
  dnn: false    # use OpenCV DNN for ONNX inference

statistic:
  db_path: mysql+pymysql://user:password@localhost/DB_NAME?unix_socket=/var/run/mysqld/mysqld.sock&charset=utf8mb4
  db_update_interval: 5    # interval(minute) to update data in database
  db_keep_day: 30   # day to keep recorded data (set to 0 to disable but make sure that you have enough disk space)