system:
  name: SmartTraffyController

stream:
  camera1_url: 2019_1120_172552_022.MOV   # stream1
  camera2_url: rtsp://192.168.1.101/live   # stream2
  camera3_url: rtsp://192.168.1.102/live   # stream3
  camera4_url: rtsp://192.168.1.103/live   # stream4

detect_area:
  camera1_area: [900, 0, 500, 1080] # x, y, width, height of camera1 for detection
  camera2_area: [x, y, w, h] # x, y, width, height of camera2 for detection
  camera3_area: [x, y, w, h] # x, y, width, height of camera3 for detection
  camera4_area: [x, y, w, h] # x, y, width, height of camera4 for detection

light:
  seqence: [3, 1, 2, 0]   # seqence of light ID
  max_timing: [45, 45, 45, 45]  # maximum green light timing
  vehicle_timing: [5, 3, 10, 15]  # timing for vehicle by type - [car, motorcycle, bus, truck]

mqtt:
  host: 192.168.1.69   # mqtt server address or hostname
  port: 1883    # mqtt server port
  username: controller    # mqtt user
  password: Nae/buf=o3jo    # mqtt password
  out_topic: SmartTraffy/controller/cmd/out # node command topic
  in_topic: SmartTraffy/controller/cmd/in # node command topic
  qos: 0    # mqtt quality of services
  version: 3.1.1    # mqtt protocol version 3.1, 3.1.1 or 5
  mac_id: true    # append mac address after system name for mqtt client id
  reconn_interval: 10   # try to reconnect every x seconds if connection lost.

yolo:
  model_path: yolov5    # model directory path
  weights: yolov5n6.pt   # model.pt path(s)
  data: data/coco128.yaml    # dataset.yaml path
  conf_thres: 0.25    # confidence threshold
  iou_thres: 0.45   # NMS IOU threshold
  max_det: 1000   # maximum detections per image
  img_size: [600,800]   # inference size h,w
  device: 0   # cuda device, i.e. 0 or 0,1,2,3 or cpu
  view_img: true    # show results
  save_txt: false   # save results to *.txt
  save_conf: false    # save confidences in --save-txt labels
  save_crop: false    # save cropped prediction boxes
  nosave: true    # do not save images/videos
  classes: [2, 3, 5, 7]   # filter by class from dataset file
  agnostic_nms: false   # class-agnostic NMS
  augment: false    # augmented inference
  visualize: false    # visualize features
  update: false   # update all models
  project: runs/detect    # save results to project/name
  name: exp   # save results to project/name
  exist_ok: false   # existing project/name ok, do not increment
  line_thickness: 2   # bounding box thickness (pixels)
  hide_labels: false    # hide labels
  hide_conf: false    # hide confidences
  half: false   # use FP16 half-precision inference
  dnn: false    # use OpenCV DNN for ONNX inference
  vid_stride: 1 # Video frame-rate stride

statistic:
  db_path: mysql+pymysql://user:password@localhost/DB_NAME?unix_socket=/var/run/mysqld/mysqld.sock&charset=utf8mb4
  db_update_interval: 5    # interval(minute) to update data in database
  db_keep_day: 30   # day to keep recorded data (set to 0 to disable but make sure that you have enough disk space)